[package]
name = "postgel-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
raunch = "1.0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "io-std", "time"] }
futures = "0.3"
